DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE SIGN_SEQ;

DROP TABLE USERS;
DROP TABLE SIGN_DOC;
DROP TABLE SIGN_GROUP;
DROP TABLE SIGN_FILE;

CREATE SEQUENCE USERS_SEQ INCREMENT BY 1;
CREATE SEQUENCE SIGN_SEQ INCREMENT BY 1;

CREATE TABLE USERS( -- 사용자테이블
USER_CODE NUMBER, -- 사용자코드
USER_ID VARCHAR2(30) NOT NULL, -- 아이디
USER_PW VARCHAR2(30) NOT NULL, -- 비밀번호
NAME VARCHAR(20), -- 이름
PHONE VARCHAR2(20), -- 전화번호
RANK VARCHAR(20), -- 직급
INS_DATE DATE DEFAULT SYSDATE, -- 입사일자
PRIMARY KEY (USER_ID)
);

CREATE TABLE SIGN_DOC( -- 결재문서 테이블
DOC_CODE NUMBER NOT NULL, -- 결재번호
USER_ID VARCHAR2(30) NOT NULL, -- 작성자아이디
NAME VARCHAR2(20), -- 작성자이름
TITLE VARCHAR2(100), -- 제목
CONTENT LONG, -- 내용
WRITEDATE DATE DEFAULT SYSDATE, -- 작성일자
SIGN_TURN NUMBER, -- 결재순서
DOC_STATUS NUMBER, -- 문서상태(0 임시저장, 1 대기중, 2 심사중, 3 반려, 4 결재완료)
COMPLETE_DATE DATE, -- 결재완료일자
PRIMARY KEY (DOC_CODE), 
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE SIGN_GROUP( -- 결재자 테이블
DOC_CODE NUMBER NOT NULL, -- 결재번호
USER_ID VARCHAR2(30) NOT NULL, -- 작성자아이디
SIGN_ID VARCHAR2(30), -- 결재자아이디
SIGN_TURN NUMBER, -- 결재순서
SIGN_TYPE VARCHAR2(20), -- 결재타입(합의, 결재)
SIGN_STATUS NUMBER DEFAULT 0, -- 결재상태(0 미결, 1 결재)
FOREIGN KEY (DOC_CODE) REFERENCES SIGN_DOC(DOC_CODE) ON DELETE CASCADE
);

CREATE TABLE SIGN_FILE( -- 결재문서 첨부파일 테이블
DOC_CODE NUMBER NOT NULL, -- 결재번호
ORGNAME VARCHAR(300), -- 파일원본이름
SYSNAME VARCHAR(100), -- 파일시스템이름
DEL_FLAG CHAR(1) DEFAULT 'N', -- 파일삭제구분
FOREIGN KEY (DOC_CODE) REFERENCES SIGN_DOC(DOC_CODE) ON DELETE CASCADE
);

INSERT INTO USERS (USER_CODE, USER_ID, USER_PW, NAME, PHONE, RANK, INS_DATE) VALUES (USERS_SEQ.nextval, 'user1', 'user', '강사장', '010-1111-1111', '사장', TO_DATE('2016-01-10','yyyy-mm-dd')); 
INSERT INTO USERS (USER_CODE, USER_ID, USER_PW, NAME, PHONE, RANK, INS_DATE) VALUES (USERS_SEQ.nextval, 'user2', 'user', '최부사장', '010-2222-2222', '부사장', TO_DATE('2016-02-24','yyyy-mm-dd')); 
INSERT INTO USERS (USER_CODE, USER_ID, USER_PW, NAME, PHONE, RANK, INS_DATE) VALUES (USERS_SEQ.nextval, 'user3', 'user', '박이사', '010-3333-3333', '이사', TO_DATE('2017-04-07','yyyy-mm-dd')); 
INSERT INTO USERS (USER_CODE, USER_ID, USER_PW, NAME, PHONE, RANK, INS_DATE) VALUES (USERS_SEQ.nextval, 'user4', 'user', '김부장', '010-4444-4444', '부장', TO_DATE('2017-11-30','yyyy-mm-dd')); 
INSERT INTO USERS (USER_CODE, USER_ID, USER_PW, NAME, PHONE, RANK, INS_DATE) VALUES (USERS_SEQ.nextval, 'user5', 'user', '박차장', '010-5555-5555', '차장', TO_DATE('2018-07-06','yyyy-mm-dd')); 
INSERT INTO USERS (USER_CODE, USER_ID, USER_PW, NAME, PHONE, RANK, INS_DATE) VALUES (USERS_SEQ.nextval, 'user6', 'user', '이과장', '010-6666-6666', '과장', TO_DATE('2018-03-21','yyyy-mm-dd')); 
INSERT INTO USERS (USER_CODE, USER_ID, USER_PW, NAME, PHONE, RANK, INS_DATE) VALUES (USERS_SEQ.nextval, 'user7', 'user', '서대리', '010-7777-7777', '대리', TO_DATE('2019-06-22','yyyy-mm-dd')); 
INSERT INTO USERS (USER_CODE, USER_ID, USER_PW, NAME, PHONE, RANK, INS_DATE) VALUES (USERS_SEQ.nextval, 'user8', 'user', '송주임', '010-8888-8888', '주임', TO_DATE('2019-09-09','yyyy-mm-dd')); 
INSERT INTO USERS (USER_CODE, USER_ID, USER_PW, NAME, PHONE, RANK, INS_DATE) VALUES (USERS_SEQ.nextval, 'user9', 'user', '한사원', '010-9999-9999', '사원', TO_DATE('2020-07-01','yyyy-mm-dd')); 
COMMIT;
